In [18]:
dataset = []
folder_paths = [
    "drive/My Drive/data/fruits-360/fruits-360-original-size/fruits-360-original-size/Training/apple_6",
    "drive/My Drive/data/fruits-360/fruits-360-original-size/fruits-360-original-size/Training/apple_braeburn_1",
    "drive/My Drive/data/fruits-360/fruits-360-original-size/fruits-360-original-size/Training/apple_crimson_snow_1",
    "drive/My Drive/data/fruits-360/fruits-360-original-size/fruits-360-original-size/Training/apple_golden_1",
    "drive/My Drive/data/fruits-360/fruits-360-original-size/fruits-360-original-size/Training/apple_golden_2",
    "drive/My Drive/data/fruits-360/fruits-360-original-size/fruits-360-original-size/Training/apple_golden_3"
]

In [19]:
import os
import cv2
for i in folder_paths:
  folder_name = os.path.basename(i)

  for file_name in os.listdir(i):
    image_path = os.path.join(i, file_name)

    if os.path.isfile(image_path):
      image = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)
      if image is not None:
        resized_image = cv2.resize(image, (250,250))
        flattened_image = resized_image.flatten().tolist()
        dataset.append(flattened_image + [folder_name])

In [20]:
import pandas as pd
df = pd.DataFrame(dataset, columns = [f"pixel {i+1}" for i in range (250*250)] + ["label"])
df

pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  pixel 7  pixel 8  \
0         255      255      255      255      255      255      255      255   
1         255      255      255      255      255      255      255      255   
2         255      255      255      255      255      255      255      255   
3         255      255      255      255      255      255      255      255   
4         255      255      255      255      255      255      255      255   
...       ...      ...      ...      ...      ...      ...      ...      ...   
1880      255      255      255      255      255      255      255      255   
1881      255      255      255      255      255      255      255      255   
1882      255      255      255      255      255      255      255      255   
1883      255      255      255      255      255      255      255      255   
1884      255      255      255      255      255      255      255      255   

      pixel 9  pixel 10  ...  pixel 62492  pixel 62493  pixel 62494  \
0         255       255  ...          255          255          255   
1         255       255  ...          255          255          255   
2         255       255  ...          255          255          255   
3         255       255  ...          255          255          255   
4         255       255  ...          255          255          255   
...       ...       ...  ...          ...          ...          ...   
1880      255       255  ...          255          255          255   
1881      255       255  ...          255          255          255   
1882      255       255  ...          255          255          255   
1883      255       255  ...          255          255          255   
1884      255       255  ...          255          255          255   

      pixel 62495  pixel 62496  pixel 62497  pixel 62498  pixel 62499  \
0             255          255          255          255          255   
1             255          255          255          255          255   
2             255          255          255          255          255   
3             255          255          255          255          255   
4             255          255          255          255          255   
...           ...          ...          ...          ...          ...   
1880          255          255          255          255          255   
1881          255          255          255          255          255   
1882          255          255          255          255          255   
1883          255          255          255          255          255   
1884          255          255          255          255          255   

      pixel 62500           label  
0             255         apple_6  
1             255         apple_6  
2             255         apple_6  
3             255         apple_6  
4             255         apple_6  
...           ...             ...  
1880          255  apple_golden_3  
1881          255  apple_golden_3  
1882          255  apple_golden_3  
1883          255  apple_golden_3  
1884          255  apple_golden_3  

[1885 rows x 62501 columns]

In [21]:
x = df.drop("label", axis =1)
x = x/255
y = df["label"]

In [22]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

y_encoded = encoder.fit_transform(y)

In [23]:
y_series = pd.Series(y_encoded, name = "Target")

df = pd.concat([x, y_series], axis = 1)
df

pixel 1  pixel 2  pixel 3  pixel 4  pixel 5  pixel 6  pixel 7  pixel 8  \
0         1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
1         1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
2         1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
3         1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
4         1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
...       ...      ...      ...      ...      ...      ...      ...      ...   
1880      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
1881      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
1882      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
1883      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   
1884      1.0      1.0      1.0      1.0      1.0      1.0      1.0      1.0   

      pixel 9  pixel 10  ...  pixel 62492  pixel 62493  pixel 62494  \
0         1.0       1.0  ...          1.0          1.0          1.0   
1         1.0       1.0  ...          1.0          1.0          1.0   
2         1.0       1.0  ...          1.0          1.0          1.0   
3         1.0       1.0  ...          1.0          1.0          1.0   
4         1.0       1.0  ...          1.0          1.0          1.0   
...       ...       ...  ...          ...          ...          ...   
1880      1.0       1.0  ...          1.0          1.0          1.0   
1881      1.0       1.0  ...          1.0          1.0          1.0   
1882      1.0       1.0  ...          1.0          1.0          1.0   
1883      1.0       1.0  ...          1.0          1.0          1.0   
1884      1.0       1.0  ...          1.0          1.0          1.0   

      pixel 62495  pixel 62496  pixel 62497  pixel 62498  pixel 62499  \
0             1.0          1.0          1.0          1.0          1.0   
1             1.0          1.0          1.0          1.0          1.0   
2             1.0          1.0          1.0          1.0          1.0   
3             1.0          1.0          1.0          1.0          1.0   
4             1.0          1.0          1.0          1.0          1.0   
...           ...          ...          ...          ...          ...   
1880          1.0          1.0          1.0          1.0          1.0   
1881          1.0          1.0          1.0          1.0          1.0   
1882          1.0          1.0          1.0          1.0          1.0   
1883          1.0          1.0          1.0          1.0          1.0   
1884          1.0          1.0          1.0          1.0          1.0   

      pixel 62500  Target  
0             1.0       0  
1             1.0       0  
2             1.0       0  
3             1.0       0  
4             1.0       0  
...           ...     ...  
1880          1.0       5  
1881          1.0       5  
1882          1.0       5  
1883          1.0       5  
1884          1.0       5  

[1885 rows x 62501 columns]

In [24]:
from sklearn.model_selection import train_test_split
import numpy as np
np.random.seed(32)
x_train, x_test, y_train, y_test = train_test_split(x, y_series, test_size = 0.2)

In [25]:
from keras.models import Sequential
model = Sequential()

In [26]:
from keras.layers import Dense, Flatten

In [27]:

model.add(Dense(128, activation='relu', input_shape=(250*250,)))


model.add(Dense(64, activation='relu'))


model.add(Dense(len(encoder.classes_), activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_3 (Dense)             (None, 128)               8000128   
                                                                 
 dense_4 (Dense)             (None, 64)                8256      
                                                                 
 dense_5 (Dense)             (None, 6)                 390       
                                                                 
Total params: 8,008,774
Trainable params: 8,008,774
Non-trainable params: 0
_________________________________________________________________


In [28]:
from keras.utils import to_categorical
y_train_encoded  = to_categorical(y_train)
y_test_encoded = to_categorical(y_test)

In [29]:
history = model.fit(x_train, y_train_encoded, batch_size = 32, epochs = 10, validation_split =0.2)

Epoch 1/10
38/38 [==============================] - 8s 180ms/step - loss: 6.4280 - accuracy: 0.4743 - val_loss: 1.8221 - val_accuracy: 0.5596
Epoch 2/10
38/38 [==============================] - 8s 214ms/step - loss: 0.9748 - accuracy: 0.7678 - val_loss: 1.0675 - val_accuracy: 0.8013
Epoch 3/10
38/38 [==============================] - 5s 129ms/step - loss: 0.3922 - accuracy: 0.8706 - val_loss: 0.1481 - val_accuracy: 0.9404
Epoch 4/10
38/38 [==============================] - 5s 121ms/step - loss: 0.9684 - accuracy: 0.8143 - val_loss: 0.1182 - val_accuracy: 0.9503
Epoch 5/10
38/38 [==============================] - 5s 136ms/step - loss: 0.2663 - accuracy: 0.8856 - val_loss: 0.1851 - val_accuracy: 0.8974
Epoch 6/10
38/38 [==============================] - 4s 104ms/step - loss: 0.1430 - accuracy: 0.9370 - val_loss: 0.0995 - val_accuracy: 0.9570
Epoch 7/10
38/38 [==============================] - 4s 112ms/step - loss: 0.1311 - accuracy: 0.9461 - val_loss: 0.1411 - val_accuracy: 0.9371
Epoch 

In [30]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
y_pred_encoded = model.predict(x_test)

y_pred = np.argmax(y_pred_encoded, axis =1)

accuracy = accuracy_score(y_test, y_pred)
print("accuracy: ", accuracy)

print(classification_report(y_test, y_pred))

conf_matrix = confusion_matrix(y_test, y_pred)
print("confusion matrix")
print(conf_matrix)

12/12 [==============================] - 0s 22ms/step
accuracy:  0.9946949602122016
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        59
           1       1.00      1.00      1.00        63
           2       1.00      1.00      1.00        61
           3       1.00      0.97      0.98        64
           4       0.98      1.00      0.99        61
           5       0.99      1.00      0.99        69

    accuracy                           0.99       377
   macro avg       0.99      0.99      0.99       377
weighted avg       0.99      0.99      0.99       377

confusion matrix
[[59  0  0  0  0  0]
 [ 0 63  0  0  0  0]
 [ 0  0 61  0  0  0]
 [ 0  0  0 62  1  1]
 [ 0  0  0  0 61  0]
 [ 0  0  0  0  0 69]]


In [31]:
model.save("dnn_model.h5")