In [1]:
import numpy as np


# task-2

In [2]:
#Make a calculator Which will base on your result scenario.

print("welcome to the faizi calculator")

def add(x,y):
    print(x+y) 

def sub(x,y):
    print(x-y)

def mul(x,y):
    print(x*y)

def div(x,y):
    print(x/y)

print("for add, type 1")
print("for sub, type 2")
print("for mul, type 3")
print("for div, type 4")

choice = int(input("selector operatio 1-4: "))

x = int(input("enter num1: "))
y = int(input("enter num1: "))


if choice == 1:
    add(x,y)
elif choice == 2:
    sub(x,y)
elif choice == 3:
    mul(x,y)
elif choice == 4:
    if x !=0:
        div(x,y)
    else:
        print("error")
else:
    print("invalid choice")
    

welcome to the faizi calculator
for add, type 1
for sub, type 2
for mul, type 3
for div, type 4
selector operatio 1-4: 2
enter num1: 34
enter num1: 32
2


## task-2

In [5]:
import math

def func(lst):
    return [x * (math.sqrt(x) - 4 * x)/x for x in lst]

# Example usage:
my_list = [2, 4, 6, 8, 10]
result = func(my_list)
print(result)


[-6.585786437626905, -14.0, -21.550510257216825, -29.17157287525381, -36.83772233983162]


### task-3

In [6]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Apply arithmetic functions on the NumPy array
add_result = np.add(arr, 2)
subtract_result = np.subtract(arr, 2)
multiply_result = np.multiply(arr, 2)
divide_result = np.divide(arr, 2)
power_result = np.power(arr, 2)
negative_result = np.negative(arr)

# Print the results
print("Original Array:", arr)
print("Addition:", add_result)
print("Subtraction:", subtract_result)
print("Multiplication:", multiply_result)
print("Division:", divide_result)
print("Power:", power_result)
print("Negative:", negative_result)


Original Array: [1 2 3 4 5]
Addition: [3 4 5 6 7]
Subtraction: [-1  0  1  2  3]
Multiplication: [ 2  4  6  8 10]
Division: [0.5 1.  1.5 2.  2.5]
Power: [ 1  4  9 16 25]
Negative: [-1 -2 -3 -4 -5]


# task-4

In [7]:
import numpy as np

# Creating an array from a list
my_list = [1, 2, 3, 4, 5]
arr1 = np.array(my_list)

# Creating an array filled with zeros
arr2 = np.zeros((3, 4))

# Creating an array filled with ones
arr3 = np.ones((2, 3, 2))

# Creating an array with a range of values
arr4 = np.arange(0, 10, 2)

# Creating an array with random values
arr5 = np.random.rand(2, 2)

# Creating an array using linspace
arr6 = np.linspace(0, 1, 5)

# Creating an identity matrix
arr7 = np.eye(3)

# Creating an array with repeated values
arr8 = np.repeat(3, 4)

# Printing all arrays
print("Array 1:", arr1)
print("Array 2:", arr2)
print("Array 3:", arr3)
print("Array 4:", arr4)
print("Array 5:", arr5)
print("Array 6:", arr6)
print("Array 7:", arr7)
print("Array 8:", arr8)


Array 1: [1 2 3 4 5]
Array 2: [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Array 3: [[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
Array 4: [0 2 4 6 8]
Array 5: [[0.98012254 0.44378531]
 [0.71193471 0.72324217]]
Array 6: [0.   0.25 0.5  0.75 1.  ]
Array 7: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Array 8: [3 3 3 3]


## task-5

In [9]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Indexing
print("Single element at (0, 1):", arr[0, 1])
print("Row at index 2:", arr[2])
print("Column at index 1:", arr[:, 1])
# Slicing
print("Subarray from rows 0 to 1 and columns 1 to 2:")
print(arr[0:2, 1:3])

print("Subarray excluding the last row and last column:")
print(arr[:-1, :-1])

print("Every other element in the last column:")
print(arr[::2, -1])


Single element at (0, 1): 2
Row at index 2: [7 8 9]
Column at index 1: [2 5 8]
Subarray from rows 0 to 1 and columns 1 to 2:
[[2 3]
 [5 6]]
Subarray excluding the last row and last column:
[[1 2]
 [4 5]]
Every other element in the last column:
[3 9]
